[build]
  command = "pip install -r requirements-netlify.txt && python build_netlify.py"
  publish = "dist/"

[build.environment]
  PYTHON_VERSION = "3.9"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "/netlify/build-plugin"