[build]
  command = "pip install -r requirements.txt && python build_standalone.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.9"

# External packages that require system dependencies
[[build.packages]]
  name = "pillow"
  external = true

[[build.packages]]
  name = "torch"
  external = true

[[build.packages]]
  name = "torchvision"
  external = true

[[build.packages]]
  name = "opencv-python" 
  external = true

[[build.packages]]
  name = "easyocr"
  external = true